// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezgwdqegozawvuchpaor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6Z3dkcWVnb3phd3Z1Y2hwYW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTk5MDEsImV4cCI6MjA2NDUzNTkwMX0.cPKlYs6evg2bZqHe1ZRTOwBCZjrcrJpW26f-GzBVpeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);